<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Times New Roman', Times, serif; 
            width: 100%;
            height: 100%;
            background: white;
        }
        .page {
            width: 100%;
            height: 100%;
            display: flex;
            flex-direction: column;
            padding: 20px;
            position: relative;
            background: white;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 10px;
            border-bottom: 2px solid #8B7355;
        }
        .header h1 {
            font-size: 24px;
            margin-bottom: 10px;
            color: #8B7355;
        }
        .header p {
            font-size: 16px;
            color: #666;
        }
        .qr-container {
            display: flex;
            justify-content: center;
            margin: 20px 0;
        }
        .qr-container img {
            width: 150px;
            height: 150px;
        }
        .guest-info {
            text-align: center;
            margin: 20px 0;
        }
        .guest-info h2 {
            font-size: 22px;
            margin-bottom: 10px;
            color: #8B7355;
        }
        .guest-info p {
            font-size: 16px;
            margin-bottom: 5px;
            color: #666;
        }
        .guest-info .jumlah {
            font-weight: bold;
            color: #000;
        }
        .badge-vip {
            display: inline-block;
            background: #f59e0b;
            color: white;
            font-size: 16px;
            font-weight: 900;
            padding: 6px 16px;
            border-radius: 20px;
            letter-spacing: 1px;
            margin-top: 10px;
        }
        .badge-vvip {
            display: inline-block;
            background: #ef4444;
            color: white;
            font-size: 16px;
            font-weight: 900;
            padding: 6px 16px;
            border-radius: 20px;
            letter-spacing: 1px;
            margin-top: 10px;
        }
        .page-footer {
            text-align: center;
            margin-top: 20px;
            padding-top: 10px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #999;
        }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <h1>
                @if($tamu->bahasa === 'en')
                    Guest QR Code
                @else
                    QR Code Tamu Undangan
                @endif
            </h1>
            <p>Printed on: {{ date('d/m/Y H:i') }}</p>
        </div>
        <div class="qr-container">
            <img src="{{ $tamu->getQrCodeForPdf(8) }}" style="width:150px;height:150px;border:none;" />
        </div>
        <div class="guest-info">
            <h2>{{ $tamu->nama }}</h2>
            <p>
                @if($tamu->bahasa === 'en')
                    <strong>Description:</strong> {{ $tamu->deskripsi }}
                @else
                    <strong>Deskripsi:</strong> {{ $tamu->deskripsi }}
                @endif
            </p>
            <p>
                @if($tamu->bahasa === 'en')
                    <strong>Invitation Count:</strong> <span class="jumlah">{{ $tamu->jumlah_orang }}</span>
                @else
                    <strong>Jumlah Undangan:</strong> <span class="jumlah">{{ $tamu->jumlah_orang }}</span>
                @endif
            </p>
            <p>
                @if($tamu->bahasa === 'en')
                    <strong>Unique Code:</strong> {{ $tamu->kode_unik }}
                @else
                    <strong>Kode Unik:</strong> {{ $tamu->kode_unik }}
                @endif
            </p>
            @if($tamu->jenis !== 'umum')
                <div class="{{ $tamu->jenis === 'VVIP' ? 'badge-vvip' : 'badge-vip' }}">
                    {{ $tamu->jenis }}
                </div>
            @endif
        </div>
        <div class="page-footer">
            <p>Generated by Undangan System</p>
        </div>
    </div>
</body>
</html>
